# For development
version: "3.1"

services:
  db:
    image: "mysql:5.7"
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: spring
      MYSQL_DATABASE: spring
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
