# Global config
spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: warn
---
# Dev config
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/dev;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
  jpa:
    database: h2
    show-sql: true
logging:
  level:
    root: info
