spring:
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: prod

---

spring:
  profiles: dev
  datasource:
    url: "jdbc:mysql://192.168.99.100:33060/spring"
    username: spring
    password: spring
  jpa:
    show-sql: true
