# Global config
spring:
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: prod
---
# Dev config
spring:
  profiles: dev
  datasource:
    username: spring
    password: spring
  jpa:
    show-sql: true
