# Global config
spring:
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: prod
---
# Dev config
spring:
  profiles: dev
  datasource:
    url: "jdbc:mysql://192.168.99.100:33060/spring?useUnicode=true&characterEncoding=utf-8"
    username: spring
    password: spring
  jpa:
    show-sql: true
