# Global config
spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: warn
---
# Dev config
spring:
  profiles: dev
  datasource:
    username: spring
    password: spring
  jpa:
    show-sql: true
